### ISSUE TITLE
The status (CPU, MEM, DISK) of ARTIK board can not show, after open the terminal.

### ISSUE THREAD

**Issue by ZhangHangdong** [codenvy/artik-ide#107] opened 2016-08-16 01:31 UTC
**Description of problem:**
The status (CPU, MEM, DISK) of ARTIK board can not show, after open the terminal.

**ARTIK IDE version:** samsung-artik-ide-nightly.zip 2016-08-14 
**ARTIK IDE install directory:** C:\artik-ide-0.1.0-RC3-SNAPSHOT
**Docker version:** 1.12.0
**Java version:** 1.8.0_101
**Environment details:** VirtualBox + samsung-artik-ide-nightly.zip
**Browser:** Firefox 47.0.1

**Steps to Reproduce:**
1. Connect ARTIK board to project correctly.
2. Open the terminal of the ARTIK board.
3. Move the mouse on the ARTIK device's status button

**Actual Results:**
The status of ARTIK board can not show, when I move mouse onto ARTIK device. (Firefox)
![issue_2-2](https://cloud.githubusercontent.com/assets/20865878/17685018/2f77f2b0-6315-11e6-94b4-7685b77bb394.PNG)

**Expected Results:**
The status of ARTIK board can show, no matter open the terminal or not.
BTW: if not open the terminal, the status can show normally.
![issue_2-1](https://cloud.githubusercontent.com/assets/20865878/17685176/789b376c-6316-11e6-9c3e-1af9265fce6e.PNG)

**Comment by eivantsov** [comment] 2016-08-16 10:25
@ZhangHangdong I cannot reproduce this one with the latest release which is 1.0.0. 

![artik](https://cloud.githubusercontent.com/assets/5337267/17695773/cd4677bc-63b2-11e6-8740-a8a8d991eeb5.png)

**Comment by ZhangHangdong** [comment] 2016-08-16 18:00
@eivantsov It seems you used Chrome, yes, the issue is not existed in Chrome. 
I am using Firefox 47.0.1, and I checked it again with version 1.0.0, the issue still existed when I used Firefox.

**Comment by ddementieva** [comment] 2016-08-18 08:32
@ZhangHangdong Bug confirmed.

**Comment by bmicklea** [comment] 2016-08-25 16:48
@ZhangHangdong - FYI, this is scheduled for the Aug-31 ARTIK IDE release.

**Comment by eivantsov** [comment] 2016-08-30 12:54
Fixed by https://github.com/eclipse/che/pull/2261

**Closed** 2016-08-30 12:55 UTC
Labels: kind/bug, status/in-progress
