### ISSUE TITLE
Error while starting artik-ide.sh

### ISSUE THREAD

**Issue by v-prabhu** [codenvy/artik-ide#298] opened 2017-01-25 19:24 UTC
Hi,
I am trying to setup the IDE from scratch. Followed the instruction provided in "https://eclipse.org/che/docs/artik/start-windows/index.html". When I start using "artik-ide.sh start" I am getting the following error. However I was not getting this error with the previous startup script.

INFO: ARTIK-IDE: Starting container...
time="2017-01-25T19:21:23Z" level=fatal msg="Error response from daemon: oci run
time error: exec: \"/home/user/che/bin/docker.sh\": stat /home/user/che/bin/dock
er.sh: no such file or directory"

Please suggest if I am doing anything wrong.

**Comment by eivantsov** [comment] 2017-01-26 14:39
@v-prabhu can you please refer to updated docs? https://github.com/eclipse/che-docs/blob/master/src/main/_docs/artik-ide-plugin/artik-start-windows.md

**Comment by v-prabhu** [comment] 2017-01-26 19:49
Using the doc, now I am able to setup the IDE. However creating workspace after launching IDE in browser does not show up. Keep getting the loading animation and never comes up. The workspace state is Running in the "Workspace" tab.
![capture](https://cloud.githubusercontent.com/assets/21373498/22347621/75db86b2-e3bd-11e6-9e47-c8469adc1c85.PNG)

**Comment by eivantsov** [comment] 2017-01-27 08:37
Duplicate of https://github.com/codenvy/artik-ide/issues/300

Let's track https://github.com/codenvy/artik-ide/issues/300

**Closed by eivantsov** 2017-01-27 08:37 UTC
Labels: kind/question
