### ISSUE TITLE
Artik Che is not downloading

### ISSUE THREAD

**Issue by v-prabhu** [codenvy/artik-ide#140] opened 2016-09-01 00:26 UTC
Hi, I am trying to install Artik Che in my Windows 7 system. But unable to download the expected Artik Che. Always landing up pulling/downloading the files for Eclipse-che.
Used following steps to configure and install Artik Che:
1) Downloaded and installed Docker 1.12.0
2) Used "docker run hello-world" to verify the docker. This worked fine.
3) Used following commands to download artik-ide.bat and artik-ide.sh files:
        a) curl -sL https://raw.githubusercontent.com/codenvy/artik-ide/master/artik-ide.sh > artik-ide.sh
        b) curl -sL https://raw.githubusercontent.com/codenvy/artik-ide/master/artik-ide.bat > artik-ide.bat
4) Set the path of the artik-ide using "set CHE_DATA_FOLDER=/c/Users/v.prabhu/Artik-ide".
5) Started artik-ide using "./artik-ide.sh start"
6) The command started pulling image for Eclipse-Che instead of Artik-Che. Please refer the folloing image. (Docker Logs: **INFO: ECLIPSE CHE: Pulling image codenvy/che-server:latest**)
![capture1](https://cloud.githubusercontent.com/assets/21373498/18150958/cf2a41f0-6f9f-11e6-891f-695d92282b68.PNG)
![capture1](https://cloud.githubusercontent.com/assets/21373498/18150964/dd3dc28a-6f9f-11e6-800d-b0aced53dc42.PNG)

Please help to resolve the issue.

Thanks,
Venkatesh

**Comment by TylerJewell** [comment] 2016-09-01 00:30
Hi @v-prabhu - let's see if we can help you out.

It seems that you are inside the bash shell when you should be in the dos prompt. Can you just open up a DOS prompt and run `artik-ide info` and provide the results?

If this continues to report the `codenvy/che-server` then I am rather perplexed, so I would ask you to then do:
```
set CHE_VERSION=nightly
artik-ide start
```

**Comment by eivantsov** [comment] 2016-09-01 06:56
@v-prabhu you can also set the latest version:

`set CHE_VERSION=latest`

**Comment by ZhangHangdong** [comment] 2016-09-01 17:39
Hi,
Please see the attached screenshot for artik-ide info in DOS command prompt.
![capture2](https://cloud.githubusercontent.com/assets/20865878/18177740/62b32636-7030-11e6-9230-616f5d936d95.PNG)

**Comment by TylerJewell** [comment] 2016-09-01 17:43
@v-prabhu - we think we have uncovered a bug in the launcher. YOu can fix this by saying `set CHE_VERSION=nightly`, and it should overcome the problem.  We are researching a fix.  We suspect it is an issue with DockerHub - as the "latest" image is tagged properly, but for some reason it keeps downloading the old one!

**Comment by TylerJewell** [comment] 2016-09-01 18:43
@v-prabhu - we found a small bug in the CLI.  We have issued a corrective fix - and it should be good now.  The issue was that if there were no CHE_ variables set, then the wrong configuration was being loaded.  This updated pull request will solve the issue.  If you re-curl the file, you will not have this problem again.

https://github.com/codenvy/artik-ide/pull/144

**Comment by eivantsov** [comment] 2016-09-02 06:12
@v-prabhu @ZhangHangdong please let me know if this fix helps.

**Comment by ZhangHangdong** [comment] 2016-09-02 16:32
@eivantsov @TylerJewell Actually. I and @v-prabhu  have the same configurations (we both set CHE_DATA_FOLDER=%userprofile%/%subdirectory%) and command steps. But we got the different result. I installed Artik IDE (right), but @v-prabhu installed Che (wrong).

@v-prabhu also set CHE_VERSION=nightly, but still installed Che (wrong). 

But After he set CHE_DATA_FOLDER=/C/Users, it fixed. Amazing! (he used boot2docker)

**So I guess the reason is his username is "v.prabhu", and there is a dot in it. The dot in the CHE_DATA_FOLDER path make it install Che, not Artik IDE.**

Could you please check it, and let me know am I right?

**Comment by TylerJewell** [comment] 2016-09-02 21:50
Gentlemen - I can confirm that there is a bug with both windows directories that have a space in them AND with directories that have a period in them.  We will explore scenarios on how we can resolve this.

**Comment by TylerJewell** [comment] 2016-09-02 23:36
Hi everyone - we may have found some solutions to the windows paths with spaces and dots in them.  We are testing some fixes with Che.  If these improvements pass the QA cycle, then we may have a solution.  We just tested this on windows with boot2docker on a directory with spaces and dots and it passed.  We need to test on Mac, docker for windows, ubuntu, and centos.

https://github.com/eclipse/che-dockerfiles/pull/8

**Comment by TylerJewell** [comment] 2016-09-05 14:58
@ZhangHangdong @v-prabhu - we have solve this issue.  It is fixes in the che-launcher. They were merged today and then will be available as part of the nightly image starting tonight.  As long as you do an `artik-ide update --force` starting tomorrow morning (get latest CLI), then you should be able to set CHE_DATA_FOLDER to a directory with a period or a space.

**Closed by TylerJewell** 2016-09-05 14:58 UTC
Labels: kind/bug
