### ISSUE TITLE
Multiple error message pop ups for Connection lost with terminal

### ISSUE THREAD

**Issue by v-prabhu** [codenvy/artik-ide#190] opened 2016-10-27 18:08 UTC
Multiple error message pop ups for Connection lost with terminal.
![multiple errors](https://cloud.githubusercontent.com/assets/21373498/19779363/a34b1312-9c35-11e6-8d1d-2d336dded09f.PNG)
![multiple errors for new workspace](https://cloud.githubusercontent.com/assets/21373498/19779367/a6e09060-9c35-11e6-8caa-a9eb4acda58c.PNG)

**Comment by eivantsov** [comment] 2016-10-30 07:49
Duplicate of https://github.com/codenvy/artik-ide/issues/191

**Closed by eivantsov** 2016-10-30 07:49 UTC
