### ISSUE TITLE
Cannot open the terminal of ARTIK board, after connect multiple boards.

### ISSUE THREAD

**Issue by ZhangHangdong** [codenvy/artik-ide#108] opened 2016-08-16 01:55 UTC
**Description of problem:**
If connect more than one board to the project, the terminal of the board cannot be opened except the last one.

**ARTIK IDE version:** samsung-artik-ide-nightly.zip 2016-08-14 
**ARTIK IDE install directory:** C:\artik-ide-0.1.0-RC3-SNAPSHOT
**Docker version:** 1.12.0
**Java version:** 1.8.0_101
**Environment details:** VirtualBox + samsung-artik-ide-nightly.zip
**Browser:** Firefox 47.0.1

**Steps to Reproduce:**
1. Create a project.
2. Connect ARTIK board 1 to the project.
3. Coneect ARTIK board 2 to the project.
4. Open the terminal of ARTIK board 1.
![issue_3](https://cloud.githubusercontent.com/assets/20865878/17685368/0ba09c54-6318-11e6-87c2-974bcad3fc08.PNG)

**Actual Results:**
Cannot open the terminal, when I move mouse onto ARTIK device (Firefox). As same reason as "The status (CPU, MEM, DISK) of ARTIK board...", its link: https://github.com/codenvy/artik-ide/issues/107 

plus, if connect ARTIK board 3, the terminal of board 1 and 2, cannot opened either.
![issue_3-2](https://cloud.githubusercontent.com/assets/20865878/17685527/b3ec8a02-6319-11e6-93eb-95825b2ceeda.PNG)

**Expected Results:**
The terminal can be opened

**Comment by eivantsov** [comment] 2016-08-16 10:25
@ZhangHangdong I cannot reproduce this one with the latest 1.0.0 release. I have tried it with 3 devices.

**Comment by ZhangHangdong** [comment] 2016-08-16 18:08
@eivantsov It seems you used Chrome, yes, the issue is not existed in Chrome.
I am using Firefox 47.0.1, and I checked it again with version 1.0.0, the issue still existed when I used Firefox.  As same as #107

**Comment by ddementieva** [comment] 2016-08-19 08:08
@ZhangHangdong Bug confirmed.

**Comment by bmicklea** [comment] 2016-08-25 16:48
@ZhangHangdong - FYI, this is scheduled for the Aug-31 ARTIK IDE release.

**Comment by eivantsov** [comment] 2016-08-30 12:54
Fixed by https://github.com/eclipse/che/pull/2261

**Closed by eivantsov** 2016-08-30 12:54 UTC
Labels: kind/bug, status/in-progress

**Comment by bmicklea** [comment] 2016-08-30 16:04
@eivantsov - is this part of the 1.0 release?  If so can you add the milestone label?
