### ISSUE TITLE
Some path error in "Push To Device" process

### ISSUE THREAD

**Issue by laralijuan** [codenvy/artik-ide#120] opened 2016-08-19 05:38 UTC
**Description of problem:**
1. The replication folder path doesn't work
2. The second "Push To Device" process make wrong path. 

**ARTIK IDE version:** samsung-artik-ide-1.0.0 
**ARTIK IDE install directory:** ~/samsung-artik-ide-1.0.0/
**Docker version:** 1.12.0
**Java version:** 1.8.0_101
**Environment details:** Ubuntu 14.04 LTS + Docker + JDK+ samsung-artik-ide-1.0.0
**Browser:** Chrome

**Steps to Reproduce:**
1. Create a project.
2. Add connection with ARTIK device. Change the "Project Replication Folder" from "/root" to "/root/IDE".
   ![1st connect device_connected](https://cloud.githubusercontent.com/assets/20897963/17799869/fcfe06ea-6610-11e6-96a3-449bba6cd1a3.png)
3. Create IDE folder in the ARTIK device's /root path.
   ![create ide path](https://cloud.githubusercontent.com/assets/20897963/17799873/02622d1e-6611-11e6-9dd3-4e04e68b6301.png)
4. Push the project to the ARTIK device directly.
   ![push to device](https://cloud.githubusercontent.com/assets/20897963/17799879/0cfbc802-6611-11e6-81b2-cfef28c70e2f.png)
5. The project is pushed to "/root/Project_test", the previous specified path "/root/IDE" doesn't work.
   ![push target project to device](https://cloud.githubusercontent.com/assets/20897963/17799884/1a40dc78-6611-11e6-8054-4f93578a84dd.png)
   ![empty in root-ide](https://cloud.githubusercontent.com/assets/20897963/17799910/5e3aecd4-6611-11e6-80bd-b4c29401d7e1.PNG)
6. Push the project to ARTIK by specify the path "/root/IDE".
   ![push to device specified path](https://cloud.githubusercontent.com/assets/20897963/17799916/70826f52-6611-11e6-87fe-704519f214e5.PNG)
7. The project is pushed to "/root/IDE/Project_test"
   ![list in ide](https://cloud.githubusercontent.com/assets/20897963/17800015/23959006-6612-11e6-8a4e-59d067b1fc3b.PNG)
8. Repeat the Step 6, do the second push to "/root/IDE"
9. The project is pushed to "/root/IDE/Project_test/Project_test"
   ![push to device 3rd](https://cloud.githubusercontent.com/assets/20897963/17800022/305c5194-6612-11e6-8071-22b8c9fb7f2b.PNG)

**Actual Results:**
The project is pushed to unexpected path.

**Expected Results:**
1. When specify the "Project Replication Folder" in connecting process, the project should be pushed to specified path, no the default path.
2. The project should be pushed to the right path, If the project existed previously, the overwrite should be excuted.

**Comment by eivantsov** [comment] 2016-08-19 06:55
@laralijuan Project replication folder is a directory in the device where projects from Artik IDE are automatically rsynced.

Push to device is an additional feature. By default, we push to root. However, you can specify whatever path you need.

In fact, push to device is not needed at all since all projects in the project tree are automatically replicated on the device.

So, when you connect a device, you specify replication path, and that's it. Everything you have got in the project tree will be in that directory on the device.

**Comment by laralijuan** [comment] 2016-08-19 08:19
@eivantsov Does artik-ide-1.0.0 have the automatically rsynced feature? It seems not. right?

**Comment by ddementieva** [comment] 2016-08-19 12:24
@laralijuan yes, it does.

**Comment by eivantsov** [comment] 2016-08-19 12:47
@laralijuan the best way to check it is to specify this replication path when connecting a device. Let it be a non existing path, say `/root/artik-ide`

Having connected a device, open a terminal into it, and run `ls`. You will see `/artik-ide/projects/${project-name}` path.

**Comment by laralijuan** [comment] 2016-08-22 06:58
@eivantsov As your discribed process. The project synchronizing only works on docker's default image (/Projects/), but not works on the connected artik device. Please check it. Thanks

**Comment by eivantsov** [comment] 2016-08-22 07:08
@laralijuan do you have rsync installed on the device? What device do you connect to Artik IDE?

**Comment by laralijuan** [comment] 2016-08-22 07:54
@eivantsov I test on ARTIK710, and have not installed rsycn.
Just now,  I tried to install rsync on the device, and change the device's profile to "Development".  But it cannot synchronize either.

**Comment by eivantsov** [comment] 2016-08-22 08:08
@laralijuan Yes, without rsync replication won't work.

With rsync installed, you should see a specified folder on the device.

We will include rsync to list of software that is installed as part of development profile.

**Comment by laralijuan** [comment] 2016-08-22 08:25
@eivantsov now, rync installed but rsync replication doesn't work either.
![1](https://cloud.githubusercontent.com/assets/20897963/17848214/c5964f0c-6884-11e6-87c3-9d45ea762a5f.png)

The issue I discribed is the "Push To Device" function, Let's back to it. For IDE 1.0.0, the push function remains, so I think this issue should be fixed.

**Comment by eivantsov** [comment] 2016-08-22 08:45
@laralijuan did you restart a workspace after rsync has been installed on the device?

**Comment by laralijuan** [comment] 2016-08-22 09:18
@eivantsov yes, it works now.

And about the path error in "Push To Device"，what is your opinion?

**Comment by eivantsov** [comment] 2016-08-22 09:21
@laralijuan I do not quite get what the error is. This feature is independent of rsync thing.

With push to device we use scp. The default path is /root but you can configure destination path when pushing to a device.

**Comment by eivantsov** [comment] 2016-09-02 07:01
@laralijuan is the behavior clear for you now?

**Comment by laralijuan** [comment] 2016-09-05 06:07
@eivantsov For the "sync project files" feature, it is OK.
For the "Push to Device", IDE 1.0.0 has the path error when doing the second "Push to Device" operation.
you can reproduce the issue by my aboved description (step 6~9)

**Comment by bmicklea** [comment] 2016-11-24 16:08
@laralijuan can you reproduce the push to device issue on ARTIK 1.2.2?

**Comment by eivantsov** [comment] 2016-12-07 13:18
@laralijuan We will close the issue since we cannot reproduce it.

**Closed by eivantsov** 2016-12-07 13:18 UTC
Labels: kind/question
