### ISSUE TITLE
IDE Workspace never comes up - Always loading

### ISSUE THREAD

**Issue by v-prabhu** [codenvy/artik-ide#299] opened 2017-01-26 19:12 UTC
Hi, Followed the steps from "https://github.com/eclipse/che-docs/blob/master/src/main/_docs/artik-ide-plugin/artik-start-windows.md" to setup the IDE in windows. I could successfully setup IDE in my system. 
Now, when I create a workspace, the screen displays only progress animation but the workspace never comes up. Tried this multiple times. But the same issue. Note that, workspace status in "Workspace" tab shows "Running".
![workspace running](https://cloud.githubusercontent.com/assets/21373498/22346237/3910f096-e3b8-11e6-89a1-3358ea5551c3.PNG)
![workspace not coming up](https://cloud.githubusercontent.com/assets/21373498/22346246/3fdd3fc4-e3b8-11e6-8506-8e794ff976e6.PNG)

**Comment by eivantsov** [comment] 2017-01-27 08:37
Duplicate of https://github.com/codenvy/artik-ide/issues/300

**Closed by eivantsov** 2017-01-27 08:37 UTC
