### ISSUE TITLE
Multiple error messages "Failed to connect terminal" even if the new workspace is created

### ISSUE THREAD

**Issue by v-prabhu** [codenvy/artik-ide#191] opened 2016-10-27 18:09 UTC
Delete workspace to which Artik board is connected. Create new workspace. Multiple error messages "Failed to connect terminal" pop up. Though the attached device no longer available with the new workspace.
![multiple errors for new workspace](https://cloud.githubusercontent.com/assets/21373498/19779395/cbbccdcc-9c35-11e6-8b4e-d678fdfa11f0.PNG)

**Comment by eivantsov** [comment] 2016-10-31 07:25
@v-prabhu can you reliably reproduce it?

FYI, in the current master terminal is delivered as an agent, i.e uses a different delivery mechanism. I cannot reproduce this one.

**Comment by v-prabhu** [comment] 2016-11-08 00:18
Hi, I can reproduce this every time when the device disconnects or update the workspace and restart. 
![restartwprkspace-afterupdate-multiple error messages](https://cloud.githubusercontent.com/assets/21373498/20081652/d9bce0f0-a505-11e6-9489-c0d6b1ce1846.PNG)

**Comment by eivantsov** [comment] 2016-11-08 09:59
I see. It is related to https://github.com/codenvy/artik-ide/issues/203 and will be fixed.

**Comment by bmicklea** [comment] 2016-11-24 16:01
@v-prabhu please update to the latest ARTIK version (1.2.2) and try again, it should be fixed now.

**Closed by bmicklea** 2016-11-24 16:01 UTC
Labels: kind/question
