### ISSUE TITLE
[Critical] If "vagrant up" under network disconnection once, "vagrant up" cannot be started anymore.

### ISSUE THREAD

**Issue by ZhangHangdong** [codenvy/artik-ide#121] opened 2016-08-19 17:43 UTC
**Description of problem:**
If we run "vagrant up" under network disconnection once, "vagrant up" cannot be started anymore after recover the network connection (I think it should be started).

**ARTIK IDE version:** artik-ide-1.0.0 (vagrant)
**ARTIK IDE install directory:** C:\
**Docker version:** 1.12.0
**Java version:** 1.8.0_101
**Environment details:** VirtualBox + Vagrant
**Browser:** Chrome

**Steps to Reproduce:**
1. Run command: “vagrant suspend” to stop the ARTIK IDE normally.
2. Disconnect all network connection, such as pull out the cable, or close the wireless.
3. Run command “vagrant up”. It will not be started. (This is correct)
4. Recover network connection.
5. Run command "vagrant up" again. 

**Actual Results:**
After recover network connection, "vagrant up" cannot be started anymore. 
![image](https://cloud.githubusercontent.com/assets/20865878/17818115/ef8007b2-65f6-11e6-92ad-244a5082da13.png)

**Expected Results:**
If I recover network connection, "vagrant up" should be started.

**Comment by TylerJewell** [comment] 2016-08-19 18:32
I can confirm the issue.  Though, I'd like to label this as a "won't fix", @ZhangHangdong.  We are working on improvements to the installation of the ARTIK IDE so that it can use the new Che launcher syntax.  It's tremendously more simplified, follows good 12-factor app design, and has a syntax that is consistent for very OS. Net net - it's a lot simpler than the Vagrant syntax.  We hope to release this in 1-2 weeks.  We have it testing now.  

The syntax that would be used to start / stop ARTIK IDE would be similar to:
https://eclipse-che.readme.io/docs/usage-docker

**Comment by eivantsov** [comment] 2016-08-21 06:09
@TylerJewell why is it labeled as a bug? This is default Vagrant behavior where Vagrant is checking if there's an updated image.

**Comment by TylerJewell** [comment] 2016-08-22 13:58
Hmm.  Can you elaborate a little bit more?  In this particular scenario, after the network was recovered, shouldn't vagrant up work normally?  It did not for me - either indicating the network was still down or failure inside the recovery vm.

**Comment by eivantsov** [comment] 2016-08-23 07:40
@TylerJewell vagrant is checking if the image in the repository has some updates.

**Comment by TylerJewell** [comment] 2016-08-23 12:50
Yes but after it determines that there is not a new image then it doesn't complete the normal up cycle.  The provisioned doesn't seem to finish the cycle.  So vagrant is either hanging or something in the provisioner cycle is not reacting properly here.

**Comment by ZhangHangdong** [comment] 2016-08-24 00:30
Just now, I met it again even though did nothing to network, and what I want to do is just restart IDE.

![capture](https://cloud.githubusercontent.com/assets/20865878/17914196/f8b01186-6954-11e6-9f41-79339eb7e260.PNG)

So now, I have to delete VM, then "vagrant up", and wait a long long time for its downloading. 
Do we have any other way to make it work again quickly? If not, I think this is a critical issue that we must fix it before MVP release. Otherwise, I guess no one like to use it (vagrant).

**Comment by TylerJewell** [comment] 2016-08-24 03:24
Ok, the best fix here will be to make the switch vet to the new docker launcher.  The core merge can happen tomorrow and I have tested the various scenarios with Artik.  The docker launcher is so much lighter weight and avoids some of these issues with vagrant availability.

I plan to discuss with our team on the various pieces we need to finalize to roll this approach to running the Artik ide out tomorrow morning.

**Comment by bmicklea** [comment] 2016-08-25 16:47
@ZhangHangdong - we are going to be switching from using Vagrant (which has several limitations that we can't overcome like this one) to a Docker based getting started. We've been using the Docker getting started method with Eclipse Che for several weeks now and the feedback has been much more positive.

I'm going to close this issue since we're removing Vagrant.

**Comment by ZhangHangdong** [comment] 2016-08-25 17:06
@bmicklea I agree with you about remove vagrant.
But now, I want to know what is the official solution to use ARTIK IDE as a desktop IDE, it means I install IDE server and use IDE dashboard both on my laptop. 
And, have we updated the online doc? I think the online doc is one of the MVP release.

**Comment by TylerJewell** [comment] 2016-08-25 17:35
@ZhangHangdong - Last night I tested a Docker-based installation of the ARTIK IDE with a nice, simple CLI.  It was super nice.  We also have a draft of the docs ready.  However, it is not ready to be published online yet, as there are components of the overall solution that need to be updated over the next 48 hours by our CI systems.

The windows installation will go something like this:
1: Get Docker Toolbox or Docker for Windows.
2: Get the artik cli

```
> curl -sL https://raw.githubusercontent.com/codenvy/artik-ide/master/che.sh > artik-ide.sh
> curl -sL https://raw.githubusercontent.com/codenvy/artik-ide/master/che.bat > artik-ide.bat

REM Add the files to your PATH
> set PATH=<path-to-cli>;%PATH%`
```

3: Start artik-ide:
```
REM If boot2docker, set workspace storage to a subdirectory of `%userprofile%`.
REM If Docker for Windows on Windows 10, set to any directory.
REM Docker is case sensitive and requires forward slashes without colons.
> set CHE_DATA_FOLDER=/c/Users

REM Start ARTIK IDE
> artik-ide start
INFO: ARTIK-IDE: Starting launcher
INFO: ARTIK-IDE: Already have image codenvy/artikide:nightly
INFO: ARTIK-IDE: Starting container...
INFO: ARTIK-IDE: Server logs at "docker logs -f artik-ide"
INFO: ARTIK-IDE: Server booting...
INFO: ARTIK-IDE: Booted and reachable
INFO: ARTIK-IDE: http://192.168.99.100:8080
```

**Comment by ZhangHangdong** [comment] 2016-08-25 18:12
@TylerJewell Oh, it looks great! I will follow you. Thank you so much **: )**

**Comment by ZhangHangdong** [comment] 2016-08-26 01:14
@TylerJewell Sorry for disturbing you again! I met following error when I run "artik-ide start". 
![capture](https://cloud.githubusercontent.com/assets/20865878/17990902/e731e678-6aee-11e6-9f96-852af0ff4db2.PNG)

I used boot2docker, and set CHE_DATA_FOLDER = /c/Users/visitor/test
![capture](https://cloud.githubusercontent.com/assets/20865878/17990947/3f33d944-6aef-11e6-94d0-e49cc398230b.PNG)
![capture](https://cloud.githubusercontent.com/assets/20865878/17990973/6c780e16-6aef-11e6-9c1b-e10c75cc71a7.PNG)

Do you have any idea about it?

**Comment by TylerJewell** [comment] 2016-08-26 01:28
Hi!  Yes, I think I can help.  My sense is that you may be trying to outthink it.  It looks like your "declare -x is in the Linux box and not on the windows terminal.

In your windows terminal do:
```
set CHE_DATA_FOLDER=c:\Users\visitor\test
```
And then type the following.  We have logic in the CLI that converts windows directories into valid Docker volume mounts.  So give this syntax a try first and let me know how it goes.
```
artik-ide start
```

Please note - we are still setting up the various CI systems for this.  So you are getting ahead of the curve on this.  We have some more tests to do before it should work out of the box.

**Comment by ZhangHangdong** [comment] 2016-08-26 05:18
@TylerJewell Sorry, I forgot mention that my laptop is Win7. When I run "artik-ide", "artik-ide start", "docker ps" in windows terminal, both got the following error:
![capture](https://cloud.githubusercontent.com/assets/20865878/17994860/68ce3142-6b11-11e6-8e62-a49baaabdcfc.PNG)

**Comment by TylerJewell** [comment] 2016-08-26 12:37
Your first error was something about directory formatting.  But your second error means that docker is not set up in your console.  You need to follow the instructions from dockers web site about starting docker in the console with docker-machine, or you can open the docker terminal which starts it for you.

**Comment by TylerJewell** [comment] 2016-08-26 13:49
Ok - some of the important changes have been completed on the CI stuff.  This page is hidden from the table of contents, but it's visible for those that have the direct URL.  You can see the full syntax for running the ARTIK IDE using Docker.

https://eclipse-che.readme.io/v4.6/docs/getting-started

**Comment by ZhangHangdong** [comment] 2016-08-29 22:00
@TylerJewell Refer to your link, now, I can install successfully
![capture](https://cloud.githubusercontent.com/assets/20865878/18068909/99b5c42a-6df8-11e6-9178-9b61dbe89734.PNG)

But after opened dashboard, I found what I installed is eclipse che, not ARTIK IDE. I cannot find the "ARTIK" stack.
![capture](https://cloud.githubusercontent.com/assets/20865878/18068953/f1e3c688-6df8-11e6-924b-7ff00820ea45.PNG)

**Comment by TylerJewell** [comment] 2016-08-29 22:52
Hi @ZhangHangdong - there are a couple things that you need to do temporarily because we haven't officially released everything yet.  I just tested this sequence and it was good to go.

```
1: Get the latest artik-ide.bat and artik-ide.sh from master.  These have been updated this afternoon with some important changes.  Make sure you override any old ones that you have.

# Configure Che to use the nightly builds
# This is very important - as these images are only available on nightly right now.
set CHE_VERSION=nightly

# Upgrade your images to the nightly.
# The last image that is downloaded should be codenvy/artikide
# If the last image is not codenvy/artikide, let me know
artik-ide update

# Start the nightly verstion of the artik-ide
artik-ide start
```

**Comment by ZhangHangdong** [comment] 2016-08-30 00:43
@TylerJewell Wow! Great! It works. I will not afflicted by vagrant any more. Thank you very much! You are my hero!
![capture](https://cloud.githubusercontent.com/assets/20865878/18071926/5c1b6d0c-6e0e-11e6-8de8-ea181982276a.PNG)

**Comment by TylerJewell** [comment] 2016-08-30 00:43
Cool.  What do you think of this new approach?  Much simpler I think.

**Comment by ZhangHangdong** [comment] 2016-08-30 18:12
Yes. Absolutely simpler!

**Closed** 2016-08-31 18:01 UTC
Labels: kind/question
